// Writes src/bim/ifc-disciplines.generated.ts from web-ifc's schema tables.
// Run after upgrading web-ifc: `npm run gen:ifc-classes` (a unit test fails when it is stale).
import fs from "node:fs";
import { disciplineTables } from "../src/bim/ifc-schema";

export function render() {
  const lines = ["// Generated by scripts/gen-ifc-classes.ts from web-ifc's IFC schemas. Do not edit.", ""];
  for (const [name, classes] of Object.entries(disciplineTables())) {
    lines.push(`export const ${name}: readonly string[] = ${JSON.stringify(classes)};`);
  }
  return lines.join("\n") + "\n";
}

if (process.argv[1]?.endsWith("gen-ifc-classes.ts")) {
  fs.writeFileSync(new URL("../src/bim/ifc-disciplines.generated.ts", import.meta.url), render());
}
